name: string_validator
version: 0.1.4
description: Dart library for validating and sanitizing strings, especially those from user input.
homepage: https://github.com/suragch/string_validator
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.5.3